### ISSUE TITLE
Where is WireGuard

### ISSUE THREAD

**Issue by shaft8472** [fabianishere/udm-kernel#12]
Hello,

I've installed the latest pre-built kernel and it loads on boot.
```
root@ubnt:/# uname -a
Linux ubnt 4.19.152-edge3 #1 SMP Wed Dec 22 09:14:38 UTC 2021 aarch64 GNU/Linux
```

I was under the impression that WireGuard was included in this kernel. I'm not quite sure how to start WireGuard and run it in-kernel. I'm not quite sure what my next step is, can someone give me some pointers?

(The end goal is a split vpn for one client.)

**Comment by fabianishere** [comment]
WireGuard is included as a kernel module. You can load it as follows:
```bash
modprobe wireguard
```

**Comment by fabianishere** [comment]
Note that WireGuard is also included in the latest (beta) firmware from Ubiquiti.

**Comment by shaft8472** [comment]
> Note that WireGuard is also included in the latest (beta) firmware from Ubiquiti.

Now that is some good news. Will take a look!

**Comment by fabianishere** [comment]
To clarify, that is only the WireGuard kernel module that is shipped with the latest (beta) firmware. No UI support or anything.
