### ISSUE TITLE
Safe to upgrade to 1.11.4?

### ISSUE THREAD

**Issue by jonwilliams84** [fabianishere/udm-kernel#14]
Not an issue, so apologies for using this channel for this query but is it safe to go to 1.11.4?

Running 1.11.0 at the moment.

**Comment by fabianishere** [comment]
These are the changes between 1.11.0 and 1.11.4: https://github.com/fabianishere/udm-kernel/commit/560241d108617e9e36798dbbcb19e7a1b7702276

So I believe it should be safe to upgrade.

**Comment by jonwilliams84** [comment]
> These are the changes between 1.11.0 and 1.11.4: [560241d](https://github.com/fabianishere/udm-kernel/commit/560241d108617e9e36798dbbcb19e7a1b7702276)
> 
> So I believe it should be safe to upgrade.

Brill, so presumably I dont need to re-apply the edge-3 kernel post upgrade?

**Comment by fabianishere** [comment]
What do you mean by re-apply? You might need to re-install the packages since the firmware upgrade might remove the packages.

**Comment by jonwilliams84** [comment]
> What do you mean by re-apply? You might need to re-install the packages since the firmware upgrade might remove the packages.

Ah, ok...that's what I meant 👍  I'll get the RFC raised with the wife and kids and schedule in for tonight. 😂
