### ISSUE TITLE
USW-Pro-24-POE and U6-LR not adoptable

### ISSUE THREAD

**Issue by Wh1t3Rose** [fabianishere/udm-kernel#17]
So I decided to give this a go for the first time after discovering it today. I am pretty good with SSH and Linux so getting it going was a breeze. 

What wasn't was that my Switch and AP were no longer Adopted. Even after resetting the devices via SSH and button on the hardware. 

Is this expected behavior? If not any ideas what may have caused this?

**Comment by fabianishere** [comment]
That's not supposed to happen. `/var/log/messages` might give you a clue as to what's happening.

**Comment by Wh1t3Rose** [comment]
Ok thank you. Unfortunately I already rolled back to stock and readopted everything. I can't afford to break my network again today but I'll try again soon and get logs. Thanks!

**Comment by fabianishere** [comment]
The log file is persistent, so you don’t have to break your network to see what happend back then 🙂(assuming it is not a long while ago and the log file has been rotated).
