### ISSUE TITLE
Device Request UCKP

### ISSUE THREAD

**Issue by thefiredragon** [fabianishere/udm-kernel#2]
Dear all,
I found this repo here and like to ask if ubnt provide kernel sdk packagades and where to find these?
We have some unifi cloud keys gen2 pro.

At this running chrooted 3.18.44-ui-qcom kernel.

Some things we like to use like wireguard or zfs need kernel modules, so could it possible to create a own new kernel with kernel headers? 

best Regards

**Comment by fabianishere** [comment]
This repository only hosts the sources for the kernels used by the UniFi Dream Machine (Pro).

For the Cloud Key, I don't think the sources are publicly available, so your best bet is to send an email to opensource-requests@ui.com asking for the GPL sources.
