### ISSUE TITLE
Does Smart Queues setting needs to be enabled to use CAKE?

### ISSUE THREAD

**Issue by fbernier** [fabianishere/udm-kernel#21]
Hey, sorry if this is obvious but as the title says, Does the Smart Queues setting in the unifi config needs to be enabled to use CAKE? Is there some other switch that needs to be flipped on the command line ?

Thanks for this btw!

**Comment by fabianishere** [comment]
You need to manually setup CAKE via the command line. See the documentation: https://www.bufferbloat.net/projects/codel/wiki/Cake/
