### ISSUE TITLE
Kernel for 1.12.30?

### ISSUE THREAD

**Issue by docbobo** [fabianishere/udm-kernel#22]
1.12.30 has been out for a while I believe. Any plans for providing a corresponding custom kernel? Or is the kernel unchanged between 1.12.22 and 1.12.30?

**Comment by fabianishere** [comment]
I am waiting on Ubiquiti for the sources at the moment. Will let you know once I have received something.

**Comment by fabianishere** [comment]
Changes are negligible: https://github.com/fabianishere/udm-kernel/commit/fefa2393bb0012f2625c78edba3de3bb6f1f0157
