### ISSUE TITLE
Edge Kernel for new UnifiOS 1.12.30

### ISSUE THREAD

**Issue by pavanbuzz** [fabianishere/udm-kernel#24]
Hi @fabianishere, may I check if there is any plan for a new kernel release which is compatible with UnifiOS 1.12.30? My UDM is in that version, and I am unable to boot 4.19.152-edge4. 
Attaching the error message that I am receiving,
```shell
root@ubnt:/# udm-bootctl boot 4.19.152-edge4
Loading kernel 4.19.152-edge4...
Inserting kexec kernel modules...
Kernel version not supported (v1.12.30)
Make sure you have installed the latest version of udm-kernel-tools...
```

Or is there an alternative to downgrade my UnifiOS so that I can install the above kernel?

**Comment by fabianishere** [comment]
You need an updated version of `udm-kernel-tools`. I’ll try to push a new release soon.

**Comment by fabianishere** [comment]
Please update to the latest version of [udm-kernel-tools](https://github.com/fabianishere/udm-kernel-tools/releases/tag/v1.1.6)

**Comment by pavanbuzz** [comment]
Thanks a ton @fabianishere !!
