### ISSUE TITLE
Edge kernel for v1.12.33

### ISSUE THREAD

**Issue by iandrewt** [fabianishere/udm-kernel#25]
I was in the middle of patching udm-kernel-tools for v1.12.33 when I realised the UDM_COMMIT line in the `config.mk` file refers to the specific rebased commit here. Not entirely sure how to go about the rebasing process for the v1.12.33 kernel (haven't emailed Ubiquiti yet either), so I thought I'd raise it here instead for assistance/guidance

Hopefully this is the last one on the UniFi OS 1.0 line and we can start working on this for the UniFi OS 2.0/3.0 lines soon

**Comment by fabianishere** [comment]
You can try building udm-kernel-tools for v1.12.33 using the most recent commit (261fc64a700803935326bad8301bdde3f62e4f05). Usually, minor version changes do not affect the kernel ABI, so you should be able to get the kernel module to work with an older commit.

**Comment by iandrewt** [comment]
Cool, in that case I've raised this PR to add support in udm-kernel-tools https://github.com/fabianishere/udm-kernel-tools/pull/86
