### ISSUE TITLE
Kernel preparation fails

### ISSUE THREAD

**Issue by sveinerikskjelbred** [fabianishere/udm-kernel#3]
If you add the file .github/config/config.local.udm the prepare.sh fails too make a good .config
Must add -m to the line for config.local.udm Then everything works as expected
....
# Support local options
if [ -f .github/config/config.local.udm ]; then
    scripts/kconfig/merge_config.sh -m .config .github/config/config.local.udm
    CONFIG_FILES="$CONFIG_FILES .github/config/config.local.udm"
fi

**Comment by fabianishere** [comment]
What’s the error you are getting?

**Comment by sveinerikskjelbred** [comment]
if I add the following line in .github/config/config.local.udm
CONFIG_KEXEC=y

and diff against the same config without config.local.udm I get
as expected

$ diff .config ../configwithoutlocal
373c373
< CONFIG_KEXEC=y
---
 > # CONFIG_KEXEC is not set
491,492d490
< CONFIG_CRASH_CORE=y
< CONFIG_KEXEC_CORE=y


Without the addeed -m I get
which accordig to my knowledge is wrong

diff .config ../configwithoutlocal
44a45
 > CONFIG_GENERIC_IRQ_CHIP=y
124d124
< # CONFIG_CGROUP_PERF is not set
181c181
< CONFIG_PERF_EVENTS=y
---
 > # CONFIG_PERF_EVENTS is not set
227c227
< # CONFIG_ARCH_ALPINE is not set
---
 > CONFIG_ARCH_ALPINE=y
252c252
< # CONFIG_ARCH_VEXPRESS is not set
---
 > CONFIG_ARCH_VEXPRESS=y
291a292,294
 > CONFIG_PCI_INTERNAL_ALPINE=y
 > CONFIG_PCI_EXTERNAL_ALPINE=y
 > # CONFIG_PCI_EXTERNAL_ERR_ALPINE is not set
346c349
< CONFIG_SCHED_SMT=y
---
 > # CONFIG_SCHED_SMT is not set
364d366
< CONFIG_HW_PERF_EVENTS=y
371c373
< CONFIG_KEXEC=y
---
 > # CONFIG_KEXEC is not set
421a424
 > CONFIG_PM_GENERIC_DOMAINS=y
422a426,427
 > CONFIG_PM_GENERIC_DOMAINS_SLEEP=y
 > CONFIG_PM_GENERIC_DOMAINS_OF=y
434a440
 > CONFIG_CPU_IDLE_MULTIPLE_DRIVERS=y
436a443
 > CONFIG_DT_IDLE_STATES=y
441c448
< # CONFIG_ARM_CPUIDLE is not set
---
 > CONFIG_ARM_CPUIDLE=y
484,485d490
< CONFIG_CRASH_CORE=y
< CONFIG_KEXEC_CORE=y
488d492
< CONFIG_UPROBES=y
503d506
< CONFIG_HAVE_HW_BREAKPOINT=y
1325c1328
< # CONFIG_VEXPRESS_CONFIG is not set
---
 > CONFIG_VEXPRESS_CONFIG=y
1480a1484
 > CONFIG_VEXPRESS_SYSCFG=y
1637a1642
 > CONFIG_AHCI_ALPINE=y
2163c2168
< # CONFIG_SERIO_AMBAKMI is not set
---
 > CONFIG_SERIO_AMBAKMI=y
2318a2324
 > # CONFIG_I2C_VERSATILE is not set
2417c2423
< # CONFIG_GPIO_PL061 is not set
---
 > CONFIG_GPIO_PL061=y
2467a2474
 > CONFIG_POWER_RESET_VEXPRESS=y
2470a2478
 > CONFIG_POWER_RESET_ALPINE=y
2619a2628
 > # CONFIG_SENSORS_VEXPRESS is not set
2638c2647
< CONFIG_THERMAL_WRITABLE_TRIPS=y
---
 > # CONFIG_THERMAL_WRITABLE_TRIPS is not set
2646c2655
< CONFIG_THERMAL_GOV_USER_SPACE=y
---
 > # CONFIG_THERMAL_GOV_USER_SPACE is not set
2654a2664,2665
 > CONFIG_AL_THERMAL_V2=y
 > # CONFIG_AL_THERMAL_V3 is not set
2668c2679
< # CONFIG_ARM_SP805_WATCHDOG is not set
---
 > CONFIG_ARM_SP805_WATCHDOG=y
2699a2711
 > CONFIG_MFD_CORE=y
2793a2806
 > CONFIG_MFD_VEXPRESS_SYSREG=y
3402a3416
 > CONFIG_ASYNC_TX_ENABLE_CHANNEL_SWITCH=y
3413a3428
 > # CONFIG_AL_SSM_PCIE is not set
3423a3439,3442
 > CONFIG_DMA_ENGINE_RAID=y
 > CONFIG_AL_DMA=y
 > CONFIG_AL_DMA_STATS=y
 > CONFIG_AL_DMA_PCI_IOV=y
3449c3468,3470
< # CONFIG_COMMON_CLK_VERSATILE is not set
---
 > CONFIG_COMMON_CLK_VERSATILE=y
 > CONFIG_CLK_SP810=y
 > CONFIG_CLK_VEXPRESS_OSC=y
3468a3490
 > CONFIG_CLKSRC_MMIO=y
3475a3498
 > CONFIG_CLKSRC_VERSATILE=y
3539a3563
 > CONFIG_ALPINE_MSI=y
3540a3565
 > CONFIG_ALPINE_IOFIC=y
3556,3564d3580
<
< #
< # Performance monitor support
< #
< # CONFIG_ARM_CCI_PMU is not set
< # CONFIG_ARM_CCN is not set
< CONFIG_ARM_PMU=y
< # CONFIG_ARM_DSU_PMU is not set
< # CONFIG_ARM_SPE_PMU is not set
4143,4144d4158
< CONFIG_UPROBE_EVENTS=y
< CONFIG_PROBE_EVENTS=y

w

Regards
Svein_Erik Skjelbred


Den 30/07/2021 23:37, skrev Fabian Mastenbroek:

**Comment by fabianishere** [comment]
I see the problem, it should now be fixed 219ed1c and 033a0b4.
