### ISSUE TITLE
Did you consider a branch without WireGuard

### ISSUE THREAD

**Issue by WonderWhere** [fabianishere/udm-kernel#5]
Hi Fabian, thank you very much for this UDM work. Like so many others I'm really missing the igmpproxy to be able to have IPTV running.
Did you consider having a branch with the kernel with just that difference and without WireGuard?  
Thanks in advance for your time!

**Comment by fabianishere** [comment]
Is there a particular reason for you not to have WireGuard included in the kernel? Most of the changes in the edge kernel is built as kernel module (WireGuard, IP-VLAN, VXLAN and MAC-VLAN tap driver and CAKE QoS), so you shouldn't be affected (in terms of memory usage or attack surface) if you don't use that functionality.

**Comment by WonderWhere** [comment]
I can't dispute that, indeed the only drawback is the fact that it makes it harder to spot the actual differences between the stock kernel and the branch you've created. It would make it more comfortable to adopt. I will be using the built in VPN thus why I'm not interested in it.
Thankx again!

**Comment by fabianishere** [comment]
To see the difference between the stock kernel and the edge kernel, see the following file: https://github.com/fabianishere/udm-kernel/blob/master/.github/config/config.edge.udm

That contains the options that have been enabled/disabled in the edge kernel.

**Comment by WonderWhere** [comment]
Thank you again!
