### ISSUE TITLE
Which kernel with 1.10.4 or 1.11?

### ISSUE THREAD

**Issue by docbobo** [fabianishere/udm-kernel#7]
I was just trying to run a custom kernel on 1.11 because I needed multi-path. As I was told that the latest  custom kernel would be incompatible, I downgraded to 1.10.4 - and got the same response.

Is there a way for me to build a compatible kernel for 1.11 myself? What would be the right OS version for the latest edge kernel provided for download here?

Thanks

**Comment by fabianishere** [comment]
The latest build is based on firmware version 1.10.0 (which is also what udm-kernel-tools supports).

I’ll have to contact Ubiquiti in order to obtain the kernel sources for 1.11.0 or 1.10.4.

**Comment by docbobo** [comment]
Ouch. That’s more involved than I had hoped for 😂 

Is there any way to run a 1.10.0 kernel on a 1.10.4 OS? This sounds like a pretty minor difference…

**Comment by fabianishere** [comment]
Glad to hear you got it working!

There were many feature requests on the Ubiquiti forums specifically for IPTV/multicast support, so I guess they finally gave in (since the change is just a build toggle for the kernel) or this is in anticipation of built-in support for igmpproxy in the UniFi UI.

**Comment by fabianishere** [comment]
That would be nice! Maybe others could also benefit from it. :)

**Comment by TheJulianJES** [comment]
> Talking about IPTV: I got German Telekom IPTV to work, but not with your igmpproxy.conf. Interested in the diffs?

There's already some information here: https://github.com/fabianishere/udm-kernel-tools/issues/2
(Bit hard to find but maybe you want to add it there)

**Comment by docbobo** [comment]
Thank you. I'll have a look, quite a lot to read. 😉

**Comment by fabianishere** [comment]
@docbobo Could you check whether the current `udm-kernel` release works with the latest release of [udm-kernel-tools](https://github.com/fabianishere/udm-kernel-tools/releases/tag/v1.1.1).

**Comment by Broeils** [comment]
Any change of getting this to work for 1.11 ? I'm looking to build the kernel module to enable mangle so I can change TTL for multicast in iptables.

**Comment by fabianishere** [comment]
Latest version is based on firmware version v1.11.
